---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-south-1
  tasks:
   - name: terminate
     ec2: 
       region: "{{ region }}"
       wait: yes
       instance_ids: ['i-0e80e5b5c445bcd7a']
       state: stopped
