---
- hosts: localhost
  connection: local
  gather_facts: no
 

  vars:
    #ec2_access_key:
    #ec2_secret_key:
    ec2_region: ap-south-1
    ec2_image: mi-7c87d913
    ec2_instance_type: t2.micro
    ec2_keypairs: ubuntu
    ec2_security_group: mys
    ec2_instance_count: 1
    wait_for_port: 22
 
  tasks:
  - name:launch AWS instances
    Local_actoin: ec2
     access_key= "{{ ec2_access_key }}"
     secret_key= "{{ ec2_secret_key }}"
     keypairs= "{{ ec2_keypairs  }}"
     group= "{{ ec2_security_group }}"
     type= "{{ mi-7c87d913 }}"
     image= " {{ ec2_image }}"
     region= "{{ ec2_region }}"
     count= "{{ ec2_instance_count }}"
     wait= yes
    register: ec2

  - name: instance to come up
    local_action: wait_for_host={{ item.public_dns_name }}
      port={{ wait_for_port }} timeout=320 state= started
    with_items: ec2.instances

