---
- hosts: localhost
  gather_facts: no
  become: yes

  tasks:

      - name: install gitlab runner
        shell: sudo wget -O /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
        shell: sudo chmod +x /usr/local/bin/gitlab-runner
        shell: sudo useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash
        shell: sudo gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
       
      - name: start gitlab runner
        shell: sudo gitlab-runner start 

