---

- hosts: local
  gather_facts: no
  remote_user: ec2-user
  become: yes
  vars:
     project_name: maven
     project_root: /var/www/html
     project_repo: https://github.com/girigowda/maven.git
     branch: master
    
  tasks:
      - name: install git
        yum: name=git state=latest

      - name: Pull sources from the repository.
        git: repo={{project_repo}} dest={{project_root}} version={{branch}}
     
      - name: Install Apache Web Server
        yum: pkg=httpd state=latest

      - name: up and running nginx
        service: name=httpd state=started
