---

- hosts: local
  gather_facts: no
  remote_user: ec2-user
  become: yes

  tasks:

      - name: install git
        yum: name=git state=latest

      - name: Install Apache Web Server
        yum: pkg=httpd state=latest

      - git:
           repo: https://github.com/girigowda/maven.git
           dest: /girish
