---

- hosts: local
  gather_facts: no
  remote_user: ec2-user
  become: yes
  tasks:

   - name: Install Apache Web Server
     yum: pkg=httpd state=latest

   - name: up and running
     service: name=httpd state=started


