---
- hosts: localhost
  gather_facts: no
  become: yes
  vars_files:
     - git11.yml

  tasks:

      - name: Add GitLab apt key
        apt_key:
          url: https://packages.gitlab.com/gpg.key
          state: present

      - name: Install GitLab Runner dependencies
        apt:
          name: '{{ item }}'
          state: present
        with_items:
          - debian-archive-keyring
          - apt-transport-https

      - name: Install GitLab Runner
        apt:
          name: gitlab-runner install
          state: latest
          update_cache: yes
